### ISSUE TITLE
Resources not affected by order field

### ISSUE THREAD

**Issue by FlorianHyver** [NormanHuth/nova-menu-order#2]
Static field $order ignored when ordering resources.

**Comment by Muetze42** [comment]
Wich Nova Version?

Have You extends CustomResource?
```php
use NormanHuth\NovaMenuOrder\Nova\CustomResource;

class Contact extends CustomResource
```

**Comment by FlorianHyver** [comment]
The Nova Version is 3.8.0.

All my Nova resources extends CustomResources.

The solution proposed in #1 didn't fix it for me.

**Comment by Muetze42** [comment]
I'v tested it with:
normanhuth/nova-menu-order: 1.0.6
laravel/nova": 3.8.1

Without problems.

The #1 is the nova method without this package.

Is the content of the file resources/views/vendor/nova/resources/navigation.blade.php following?
```
@if (count(\Laravel\Nova\Nova::availableResources(request())))
    @foreach($navigation as $group => $resources)
        @if (count($groups) > 1)
            <h4 class="mb-0 mt-0 text-xs text-white-50% uppercase tracking-wide text-center border-t" style="padding-top: 0.5rem">{!!  $group !!}</h4>
        @endif

        <ul class="list-reset">
            @foreach($resources as $resource)
                <li class="leading-tight mb-4 text-sm">
                    <router-link :to="{
                        name: 'index',
                        params: {
                            resourceName: '{{ $resource::uriKey() }}'
                        }
                    }" class="text-white text-justify no-underline dim" style="padding-left: 20px">
                        {!!  $resource::label()  !!}
                    </router-link>
                </li>
            @endforeach
        </ul>
    @endforeach
@endif
```

**Comment by FlorianHyver** [comment]
I don't have the same file but even with your code the resources are still in alphabetical order.
Could this problem come from the fact that I overrided the label and singular label for localization ?

**Comment by Muetze42** [comment]
It is only when it is made so that translations can be used.

As long as you don't change label(), it should work.

**Comment by FlorianHyver** [comment]
I had to override `public static function label()` and `public static function singularLabel()` so that my resources would be translated in the side bar.

**Comment by Muetze42** [comment]
But the readme says how to translate it:

```php
    public static function setLabel()
    {
        return __('Contact');
    }
    public static function setSingularLabel()
    {
        return __('Contact');
    }
```

**Comment by FlorianHyver** [comment]
Thank you, my translation syntax was wrong. I didn't expect it could cause an issue with the order field and didn't pay much attention to it in the first time.
This solved my issue.
